name: Deploy

env:
  PYTHON_VERSION: '3.9'

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Renew now"
        required: false
        type: boolean

jobs:
  rebuild:
    runs-on:  ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python version
      uses: actions/setup-python@v5.2.0
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Create and start virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
      working-directory: ./

    - name: Install dependencies
      run: pip install -r requirements.txt
      working-directory: ./

    - name: renew
      run: |
        pybabel extract -F babel.cfg -o messages.pot .
        pybabel update -i messages.pot -d translations
        pybabel compile -d translations
        flask run
      working-directory: ./
